#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-desktop
    username: localminer
    password: "password"
  storage:
    layout:
      name: lvm
  packages:
    - vim
    - git

