#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-desktop
    username: localminer
    password: "password"
  storage:
    layout:
      name: direct
  packages:
    - vim
    - git
  late-commands:
    - curtin in-target -- apt update

