#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-desktop
    username: localminer
    password: "password"
  storage:
    layout:
      name: direct
    disks:
      - device: /dev/sda
        wipes: superblock
        partitions:
          - size: 20480
            type: primary
            filesystem: ext4
            mount_point: /
          - size: 10240
            type: primary
            filesystem: ext4
            mount_point: /home
  packages:
    - vim
    - git

